export const LIST = {
    INIT_LIST: 'INIT_LIST',
    UPDATE_LIST: 'UPDATE_LIST',
    EDIT_ITEM_LIST: 'EDIT_ITEM_LIST',
    ADD_ITEM_LIST: 'ADD_ITEM_LIST',
    DELETE_ITEM_LIST: 'DELETE_ITEM_LIST',
    RESET_LIST: 'RESET_LIST',
}