export const TODOS = {
    INIT_TODOS: 'INIT_TODOS',
    UPDATE_TODOS: 'UPDATE_TODOS',
    EDIT_ITEM_TODOS: 'EDIT_ITEM_TODOS',
    ADD_ITEM_TODOS: 'ADD_ITEM_TODOS',
    DELETE_ITEM_TODOS: 'DELETE_ITEM_TODOS',
    RESET_TODOS: 'RESET_TODOS',
};